# Generated by Django 4.1.3 on 2022-12-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('unique_name', models.CharField(max_length=200)),
                ('monthly_goal', models.FloatField()),
                ('initial_value', models.FloatField()),
                ('curve_type', models.IntegerField(choices=[(1, 'Linear'), (2, 'Parabolic'), (3, 'Logarithmic')])),
                ('is_default', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
