# Generated by Django 4.1.3 on 2022-12-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='description',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
