# Generated by Django 4.1.3 on 2022-12-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_counterparty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
