# Generated by Django 4.1.3 on 2022-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
