# Generated by Django 4.1.3 on 2022-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='description',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
